# Default config for ZavAutoMessager.

enabled: true

delay: 60 # In Seconds

permissionsenabled: false # If true, only people with permission can view the message.

chatformat: '[&6AutoMessager&f]: %msg'

messageinrandomorder: true # Should the messages be displayed in a random order

messages:
    - '&6Example Message'
    - 'Thanks for choosing this plugin :D!'
    - 'Test Message'
    - '&4Made by zachooo and javoris767!'