# Default config for ZavAutoMessager.

delay: 60 # In Seconds

permissions: false # If true, only people with permission can view the message.

chatformat: '[&6ZavAutoMessager&f]: %msg'

messages:
    - '&6Example Message'
    - 'Thanks for choosing this plugin :D!'
    - 'Test Message'